export const ALL_GISTS_LOADING = 'ALL_GISTS_LOADING';
export const ALL_GISTS_ERROR = 'ALL_GISTS_ERROR';
export const ALL_GISTS_SUCCESS = 'ALL_GISTS_SUCCESS';

export const GIST_FORKS_LOADING = 'GIST_FORKS_LOADING';
export const GIST_FORKS_ERROR = 'GIST_FORKS_ERROR';
export const GIST_FORKS_SUCCESS = 'GIST_FORKS_SUCCESS';
